services:
  auth:
    container_name: auth
    hostname: auth
    image: ${auth_image}
    command:
      - '--accesslog=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.http=true'
      - '--entrypoints.http.address=:80'
      - '--log=true'
      - '--log.level=ERROR'
      - '--entryPoints.http.forwardedHeaders.insecure'


